# main text of home
name: Andrew Aquino
bio: Computer Science senior @ RPI, web developer, dabbling designer, (bass) guitar nerd, cook/baker.

# twitter summary info
# description: Sometimes I tweet about stuff

# if it's an external image, update below for true
# better with square images
external-image: true
picture: https://gravatar.com/avatar/c2855f4a8d95ffa349a9a33a583639a6?size=280

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: false
resume-url: assets/resume/Andrew Aquino Resume.pdf

url: https://dawneraq.github.io

permalink: /:title/

# To enable google analytics, supply your token below
analytics-google: 'UA-92780960-1'

# if you don't want comments in your posts, leave categories empty
# disqus:
#   shortname: mydisqus # enter this from your disqus account
#   categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
email: dawneraq@gmail.com
github: dawneraq
linkedin: dawneraq
facebook: dawneraq
spotify: 12169576475
instagram: aqandrew
flickr: dawneraq
# twitter: aqandrew
# google: mygoogle
# youtube: myyoutube
# stackoverflow: 7044681/mystackoverflow
# reddit: username
# vimeo: myvimeo

# authors:
#     andrewaquino:
#         name: Andrew Aquino
#         bio: RPI junior, software/web developer, dabbling designer, (bass) guitarhead, cook/baker.
#         external-image: true
#         picture: https://en.gravatar.com/userimage/99495981/5aa15882e728c60f8dedca3bdc3109e7?size=280
#         twitter: aqandrew

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: false

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

gems:
  - jekyll-seo-tag
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Default Front Matter values
defaults:
  -
    scope:
      path: "posts"
    values:
      external-image: false
